name: StreamVaultTV
options:
  bundleIdPrefix: com.murat.streamvault
  createIntermediateGroups: true
  deploymentTarget:
    tvOS: "17.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "${BUILD_NUMBER}"
    SWIFT_VERSION: "5.0"

targets:
  StreamVaultTV:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    resources:
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.murat.streamvault.tv
        TARGETED_DEVICE_FAMILY: "3"
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        GENERATE_INFOPLIST_FILE: "NO"
        DEVELOPMENT_TEAM: SGT92DDF82
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: StreamVault
        UIUserInterfaceStyle: Dark
        CFBundleIcons:
          CFBundlePrimaryIcon: "App Icon & Top Shelf Image"
        TVTopShelfImage:
          TVTopShelfPrimaryImageWide: "App Icon & Top Shelf Image"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
