scripts:
      - name: Set up tvOS code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type TVOS_APP_STORE \
            --certificate-key "@env:CERTIFICATE_PRIVATE_KEY" \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build tvOS app (.ipa)
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"